version: '2'

services:
  app:
    container_name: "yando-app"
    build:
      dockerfile: Dockerfile
    image: "allokanic/yando"
    ports:
      - "80:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://yando-db:5432/ABOBA
      - SPRING_DATASOURCE_USERNAME=ABOBA
      - SPRING_DATASOURCE_PASSWORD=ABOBA
    depends_on:
      - postgres

  postgres:
    container_name: "yando-db"
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=ABOBA
      - POSTGRES_PASSWORD=ABOBA
      - POSTGRES_DB=ABOBA
