version: '2'

services:
  postgres:
    container_name: "yando-db"
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=ABOBA
      - POSTGRES_PASSWORD=ABOBA
      - POSTGRES_DB=ABOBA